### PR TITLE
Update to version 1.0

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
Hm, recipe rebuild removed the run-dependency `xorg-libxrender` ... all CI builds are still fine.

**Comment by dbast** [comment]
Tested this successfully on osx with an environment that does not contain any `xorg-*` packages.

I tend to merge this. Any objections?

**Comment by cbrueffer** [comment]
Looks good to me!

**Comment by dbast** [comment]
Oh, found the old discussions https://github.com/conda-forge/r-markdown-feedstock/pull/1 

Looks like removing `xorg-libxrender` for r-markdown is fine. The tricky part seems to be r-rmarkdown. 

Merging this and afterwards re-triggering https://github.com/conda-forge/r-rmarkdown-feedstock/pull/14

**Pull request merged**
